set("YAML_CPP_BUILD_TESTS" "OFF" CACHE INTERNAL "")
set("YAML_CPP_BUILD_TOOLS" "OFF" CACHE INTERNAL "")
set("CMAKE_CXX_STANDARD" "20" CACHE INTERNAL "")
set("CMAKE_CXX_FLAGS" "-stdlib=libc++" CACHE INTERNAL "")
