set("RAPIDJSON_BUILD_DOC" "OFF" CACHE INTERNAL "")
set("RAPIDJSON_BUILD_EXAMPLES" "OFF" CACHE INTERNAL "")
set("RAPIDJSON_BUILD_TESTS" "OFF" CACHE INTERNAL "")
set("CMAKE_POLICY_VERSION_MINIMUM" "3.5" CACHE INTERNAL "")
