set("WASMEDGE_BUILD_TOOLS" "OFF" CACHE INTERNAL "")
set("WASMEDGE_BUILD_PLUGINS" "OFF" CACHE INTERNAL "")
set("WASMEDGE_BUILD_STATIC_LIB" "OFF" CACHE INTERNAL "")
set("WASMEDGE_BUILD_SHARED_LIB" "OFF" CACHE INTERNAL "")
