set("LLVM_ENABLE_PROJECTS" "lld" CACHE INTERNAL "")
set("LLVM_ENABLE_PROJECTS" "${LLVM_ENABLE_PROJECTS}" "clang" CACHE INTERNAL "")
set("LLVM_TARGETS_TO_BUILD" "X86" CACHE INTERNAL "")
set("LLVM_TARGETS_TO_BUILD" "${LLVM_TARGETS_TO_BUILD}" "BPF" CACHE INTERNAL "")
