set("HUNTER_INSTALL_LICENSE_FILES" "googletest/LICENSE" CACHE INTERNAL "")
set("gtest_force_shared_crt" "TRUE" CACHE INTERNAL "")
set("CMAKE_CXX_FLAGS" "-Wno-deprecated-copy" CACHE INTERNAL "")
set("HUNTER_INSTALL_LICENSE_FILES" "googletest/LICENSE" CACHE INTERNAL "")
set("gtest_force_shared_crt" "TRUE" CACHE INTERNAL "")
